name: releaser

on:
  push:
    tags:
      - "v[0-9]+.[0-9]+.[0-9]+alpha[0-9]+"
      - "v[0-9]+.[0-9]+.[0-9]+beta[0-9]+"
      - "v[0-9]+.[0-9]+.[0-9]+rc[0-9]+"
      - "v[0-9]+.[0-9]+.[0-9]+"

jobs:
  build64:
    runs-on: windows-latest
    strategy:
      matrix:
        include:
          - msystem: CLANG64
            arch: clang-x86_64
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: recursive
      - uses: msys2/setup-msys2@v2
        with:
          msystem: ${{ matrix.msystem }}
          install: >-
            git
            mingw-w64-${{ matrix.arch }}-clang
            mingw-w64-${{ matrix.arch }}-cmake
            mingw-w64-${{ matrix.arch }}-compiler-rt
            mingw-w64-${{ matrix.arch }}-lld
            mingw-w64-${{ matrix.arch }}-ninja
            mingw-w64-${{ matrix.arch }}-tools
      - name: Run ninja
        shell: msys2 {0}
        run: |
          mkdir -p build/64bit
          cd build
          rm -f 64bit/CMakeCache.txt && cmake -S .. -B 64bit --preset 64bit && cmake --build 64bit
      - name: Upload binaries
        uses: actions/upload-artifact@v3
        with:
          name: bin64
          path: |
            build/64bit/bin/**/*
  build32:
    runs-on: windows-latest
    strategy:
      matrix:
        include:
          - msystem: CLANG32
            arch: clang-i686
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: recursive
      - uses: msys2/setup-msys2@v2
        with:
          msystem: ${{ matrix.msystem }}
          install: >-
            git
            mingw-w64-${{ matrix.arch }}-clang
            mingw-w64-${{ matrix.arch }}-cmake
            mingw-w64-${{ matrix.arch }}-compiler-rt
            mingw-w64-${{ matrix.arch }}-lld
            mingw-w64-${{ matrix.arch }}-ninja
            mingw-w64-${{ matrix.arch }}-tools
      - name: Build
        shell: msys2 {0}
        run: |
          mkdir -p build/32bit
          cd build
          rm -f 32bit/CmakeCache.txt && cmake -S .. -B 32bit --preset 32bit && cmake --build 32bit
      - name: Upload binaries
        uses: actions/upload-artifact@v3
        with:
          name: bin32
          path: |
            build/32bit/bin/**/*
  create-release:
    needs: [build64, build32]
    runs-on: ubuntu-latest
    steps:
      - name: Get the version
        id: get_version
        run: echo "tag=${GITHUB_REF/refs\/tags\//}" >> $GITHUB_OUTPUT
      - name: Download artifacts
        uses: actions/download-artifact@v3
      - name: Zip
        run: |
          cd bin64
          cp ../bin32/ffmpeg_input.aui ./ffmpeg_input-brdg64.aui
          zip -r ../package.zip *
          cd ..
      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: ${{ github.ref }}
          draft: true
          prerelease: false
          body: |
            ### ダウンロード
            
            - [ffmpeg_input_${{ steps.get_version.outputs.tag }}.zip](https://github.com/oov/aviutl_ffmpeg_input/releases/download/${{ steps.get_version.outputs.tag }}/ffmpeg_input_${{ steps.get_version.outputs.tag }}.zip)
            
            This software uses libraries from the [FFmpeg project](https://www.ffmpeg.org/) under the LGPLv2.1.  
            Copyright (c) 2003-2022 the FFmpeg developers.
            
            This software uses [OpenH264](https://github.com/cisco/openh264) binary that released from Cisco Systems, Inc.  
            OpenH264 Video Codec provided by Cisco Systems, Inc.  
            Copyright (c) 2014 Cisco Systems, Inc. All rights reserved.
            
            ### 変更点
            
            - ＊＊＊＊
      - name: Upload Release Asset
        id: upload-release-asset
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: package.zip
          asset_name: ffmpeg_input_${{ steps.get_version.outputs.tag }}.zip
          asset_content_type: application/zip
